name: Ubuntu 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu_test:
    name: Execute tests on Ubuntu
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["6.1.0"]
    runs-on: ubuntu-22.04
    env:
      OPENSWIFTUI_WERROR: 1
      OPENSWIFTUI_ATTRIBUTEGRAPH: 0
      OPENSWIFTUI_COMPATIBILITY_TEST: 0
      OPENSWIFTUI_SWIFT_LOG: 1
      OPENSWIFTUI_SWIFT_CRYPTO: 1
      OPENSWIFTUI_LINK_TESTING: 1
    container: swift:${{ matrix.swift_version }}-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Toolchain fix patch
        run: |
          # Fix swift-corelibs-foundation#5211
          .github/scripts/fix-toolchain.sh
      - name: Building and running tests in debug mode with coverage
        run: |
          swift test \
            -c debug \
            --filter OpenSwiftUITests \
            --filter OpenSwiftUICoreTests \
            --enable-code-coverage \
            --build-path .build-test-debug
          llvm-cov show \
            -instr-profile=.build-test-debug/debug/codecov/default.profdata \
            .build-test-debug/debug/OpenSwiftUIPackageTests.xctest \
            > coverage.txt
        id: debug-test
      - name: Building and running tests in release mode
        run: |
          swift test \
            -c release \
            --filter OpenSwiftUITests \
            --filter OpenSwiftUICoreTests \
            --build-path .build-test-release
        id: release-test
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true